// AgoraUIComponent.cpp
#include "AgoraUIComponent.h"
#include "AgoraBridge.h"
#include "logos_api.h"
#include "logos_api_client.h"

#include <QQuickWidget>
#include <QQmlContext>
#include <QQmlEngine>
#include <QVBoxLayout>
#include <QWidget>
#include <QUrl>
#include <QDebug>

AgoraUIComponent::AgoraUIComponent(QObject *parent) : QObject(parent) {}
AgoraUIComponent::~AgoraUIComponent() {}

QWidget *AgoraUIComponent::createWidget(LogosAPI *logosAPI)
{
    auto *container = new QWidget();
    container->setObjectName("AgoraContainer");
    container->setStyleSheet("background: #08090f;");

    auto *layout = new QVBoxLayout(container);
    layout->setContentsMargins(0, 0, 0, 0);
    layout->setSpacing(0);

    auto *quickWidget = new QQuickWidget(container);
    quickWidget->setResizeMode(QQuickWidget::SizeRootObjectToView);
    quickWidget->setAttribute(Qt::WA_AlwaysStackOnTop);
    quickWidget->setClearColor(QColor("#08090f"));

    // ── Wire bridge ───────────────────────────────────────────────
    auto *bridge = new AgoraBridge(logosAPI, quickWidget);
    quickWidget->rootContext()->setContextProperty("agora", bridge);

    // ── Route Logos events → bridge ───────────────────────────────
    if (logosAPI) {
        logosAPI->getClient("agora_module")
            ->onEvent([bridge](const QString &eventName, const QVariantList &data) {
                bridge->handleEvent(eventName, data);
            });
    }

    // ── Load QML from the registered module ───────────────────────
    // Qt6 qt_add_qml_module registers the module under "Agora" URI.
    // We load the root file via qrc path generated by qt_add_qml_module.
    quickWidget->setSource(QUrl("qrc:/qt/qml/Agora/AgoraRoot.qml"));

    if (quickWidget->status() == QQuickWidget::Error) {
        qWarning() << "[Agora] QML errors:";
        for (const auto &e : quickWidget->errors())
            qWarning() << "  " << e.toString();
    }

    layout->addWidget(quickWidget);
    return container;
}

void AgoraUIComponent::destroyWidget(QWidget *widget)
{
    delete widget;
}
